name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
        registry-url: 'https://registry.npmjs.org'

    - name: build
      run: echo Hello, world!
